name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  heroku_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "finalapp2"
        heroku_email: "johnmugisa06@gmail.com"
        usedocker: true
        docker_build_args: |
          NODE_ENV
          SECRET_KEY
      env:
        NODE_ENV: production
        SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
<<<<<<< HEAD

=======
>>>>>>> 845f03224a9557ca64c55bef0fed2e2997c2e37e
