name: Deploy

on:
  push:
    branches:
      - main  # Adapted this line to use 'main' instead of 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "finalapp2" # Using your app's name here
          heroku_email: "YOUR_EMAIL"  # Replace 'YOUR_EMAIL' with your Heroku account email
          usedocker: true
          docker_build_args: |
            NODE_ENV
            SECRET_KEY
        env:
          NODE_ENV: production
          SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}

